waypoint_navigation:
  waypoint_navigation_node:
    ros__parameters:
      wps:
        - "p0"
        - "4.1"
        - "10.2"
        - "0.02"
        - "0.0"

        - "p1"
        - "-8.8"
        - "-20.0"
        - "0.02"
        - "0.0"

        - "p2"
        - "-8.1"
        - "-5.1"
        - "0.025"
        - "1.0"

        - "p3"
        - "4.0"
        - "-27.5"
        - "0.02"
        - "1.0"

        - "p4"
        - "8.25"
        - "-21.0"
        - "0.02"
        - "1.0"

        - "p5"
        - "7.8"
        - "-6.6"
        - "0.002"
        - "1.0"
